export const CREATE_DRAGABLE_DIV = "CREATE_DRAGABLE_DIV";
export const DRAGABLEDIV_FAILED = "DRAGABLEDIV_FAILED";
export const GET_DRAGABLEDIVS = "GET_DRAGABLEDIVS";
export const SAVE_DRAGABLEDIVS = "SAVE_DRAGABLEDIVS";
